#!/usr/bin/env python3
from decouple import config
import os 
PATH = config('PATH')
INSTALL_PREFIX = config('INSTALL_PREFIX')
SOURCE_DIR = config('SOURCE_DIR')
BUILD_DIR = config('BUILD_DIR')
INSTALL_DIR = config('INSTALL_DIR')
GVM_VERSION = config('GVM_VERSION')
GVM_LIBS = config('GVM_LIBS')
GVMD_VERSION = config('GVMD_VERSION')
GSA_VERSION = config('GSA_VERSION')
OPENVAS_SMB_VERSION = config('OPENVAS_SMB_VERSION')
OPENVAS_SCANNER_VERSION = config('OPENVAS_SCANNER_VERSION')
OSPD_VERSION = config('OSPD_VERSION')
OSPD_OPENVAS_VERSION = config('OSPD_OPENVAS_VERSION')
os.system("gvmd --modify-setting 78eceaec-3385-11ea-b237-28d24461215b --value `gvmd --get-users --verbose | grep admin | awk '{print $2}'`")
os.system("sudo -u gvm greenbone-nvt-sync")
os.system("sudo -u gvm greenbone-feed-sync --type SCAP")
os.system("sudo -u gvm greenbone-feed-sync --type CERT")
os.system("sudo -u gvm greenbone-feed-sync --type GVMD_DATA")
